### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.pitivi.Pitivi#13]

**Comment by thiblahute** [comment]
This was done in our build env, so it should be quite straight forward, see https://gitlab.gnome.org/GNOME/pitivi/blob/master/build/flatpak/org.pitivi.Pitivi.json

**Comment by muelli** [comment]
any chance you can put the manifest here so that flathub users can benefit from the newer runtime?

**Comment by aleb** [comment]
We need to test 3.34 first

**Comment by hfiguiere** [comment]
This will be closed by #17 as it will use 3.36
