### ISSUE TITLE
flathub search for "video" does not yield pitivi

### ISSUE THREAD

**Issue by muelli** [flathub/org.pitivi.Pitivi#14]
I think it's bit weird to not find pitivi when searching for "video". https://flathub.org/apps/search/video
I don't know what data is used there, but I suggest Pitivi to do some SEO there ;)

**Comment by hfiguiere** [comment]
The backend on flathub also has serious limitations

**Comment by thiblahute** [comment]
I am not sure about how to make that happen, how does flathub handle seaches?

**Comment by hfiguiere** [comment]
In the "summary" of the appdata file is says "Create and edit your own movies". Sadly it doesn't seem that the description is searched.
Search for "create and edit" I get both Pitivi and Synfig that have these words.

**Comment by thiblahute** [comment]
Yeah, and `movies` also find Pitivi, we could say "Create and edit your own videos and movies" but... meh :-)

**Comment by hfiguiere** [comment]
This would be flathub/linux-store-frontend#137

**Comment by hfiguiere** [comment]
This was fixed with the above issue. (I can't close this issue)

**Comment by thiblahute** [comment]
Thanks !
