### ISSUE TITLE
Remove dconf workaround

### ISSUE THREAD

**Issue by eszlari** [flathub/org.pitivi.Pitivi#19]
https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

**Comment by thiblahute** [comment]
We do not use dconf, what workaround are you talking about?

**Comment by eszlari** [comment]
https://github.com/flathub/org.gnome.Totem/commit/df4cc18226c390a271fb3102c65d28f99bf36b45

**Comment by thiblahute** [comment]
Can you make a patch?

**Comment by eszlari** [comment]
> Can you make a patch?

I don't know the value for `--metadata=X-DConf=migrate-path=`.

**Comment by hfiguiere** [comment]
Will be part of #34
