### ISSUE TITLE
Won't launch on F36 due to missing icon

### ISSUE THREAD

**Issue by Willdrick** [flathub/org.pitivi.Pitivi#30]
Pitivi (downloaded from Flathub) wasn't launching from the app grid, launching from the terminal I get the following output:
`gi.repository.GLib.GError: gtk-icon-theme-error-quark: El icono «dialog-question» no está presente en el tema Adwaita (0)`
Roughly translating to "«dialog-question» icon is not present in the theme Adwaita (0)"

This is on Fedora 36 SilverBlue with Flathub repo added. I have some adwaita packages (org.kde.KStyle.Adwaita and org.gtk.gtk3theme.adw-gtk3) as well as gnome platform flatpak

**Comment by aleb** [comment]
This is https://gitlab.gnome.org/GNOME/pitivi/-/issues/2600 and has been fixed. We still need to do a release to distribute the fix. Some remaining issues to be fixed though. https://gitlab.gnome.org/GNOME/pitivi/-/milestones/9#tab-issues

**Comment by hfiguiere** [comment]
build 22.06 is available now. It should be fixed.
