### ISSUE TITLE
Pitivi not launching on custom cursor theme setup (Solution)

### ISSUE THREAD

**Issue by realmazharhussain** [flathub/org.pitivi.Pitivi#31]
As you can see in [this issue](https://gitlab.gnome.org/GNOME/pitivi/-/issues/2624) in Pitivi GitLab, a lot of users are experiencing Pitivi refusing to launch when a cursor theme other than Adwaita is used.

This was an issue in matplotlib and has been fixed in v3.4.0. So, I request you to update matplotlib to the newest version to fix this issue once and for all.

**Comment by hfiguiere** [comment]
22.06 is available now. Should be fixed.
