### ISSUE TITLE
Update to 23.03

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.pitivi.Pitivi#35]
There is a tag for 23.03.

(albeit I see no update on the website)

**Comment by AsciiWolf** [comment]
Any news about the update? It is mentioned [here](https://www.pitivi.org/news/2023-03-26-pitivi-2023-03-time-was-money/) ("You should be able to upgrade to Pitivi 2023.03 when we update flathub".), however the Flatpak still was not updated to this day.

**Comment by aleb** [comment]
Thanks for asking. No, there is no update. It's still on the TODO list.

**Comment by hfiguiere** [comment]
Had I had an answer back in April I would have done it when I had more free time...
