### ISSUE TITLE
Get codecs in a extension

### ISSUE THREAD

**Issue by thiblahute** [flathub/org.pitivi.Pitivi#6]
For legal reason we should not "force" user to install those and thus we should have them in a flatpak extension.

**Comment by ramcq** [comment]
See the runtime's new "cut down" ffmpeg and the full version in the extension - if Pitivi can link to the runtime's ffmpeg as default, and upgrade if Pitivi.Codecs extension is installed (containing the "full" ffmpeg, x265, etc) then we can avoid installing the codecs extension if needed.

**Comment by TingPing** [comment]
Neither of those are useful to Pitivi since they are decoders only.

**Comment by ramcq** [comment]
@TingPing GStreamer typically wraps encoders directly, and uses ffmpeg for decoders. And actually, most "free" codecs have their own encoders/decoders in GStreamer too. So for Pitivi I expect this will mostly only affect the "non-free" codecs in ffmpeg which we want to limit. And, if they do need exciting encoders from ffmpeg - the Pitivi.Codecs can provide a more full ffmpeg than org.freedesktop.Platform.ffmpeg.

**Comment by thiblahute** [comment]
This is done, closing.
